"""add type column to events

Revision ID: 106383c9d4ce
Revises: e6fed5d6c27d
Create Date: 2026-03-14 15:17:48.618842
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106383c9d4ce'
down_revision = 'e6fed5d6c27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False, server_default='Other'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###